"""add course pdf_path

Revision ID: 48e1ed9ac0f3
Revises: de74fd253366
Create Date: 2026-02-21 14:23:51.949277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48e1ed9ac0f3'
down_revision: Union[str, None] = 'de74fd253366'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('pdf_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'pdf_path')
    # ### end Alembic commands ###
