"""remove course pdf path

Revision ID: 510517af1360
Revises: 48e1ed9ac0f3
Create Date: 2026-02-21 16:13:07.893766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '510517af1360'
down_revision: Union[str, None] = '48e1ed9ac0f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'pdf_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('pdf_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
