"""add course_id to generation_runs

Revision ID: de74fd253366
Revises: 359e9a621e25
Create Date: 2026-02-20 21:14:21.155186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de74fd253366'
down_revision: Union[str, None] = '359e9a621e25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation_runs', sa.Column('course_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_generation_runs_course_id'), 'generation_runs', ['course_id'], unique=False)
    op.create_foreign_key(None, 'generation_runs', 'courses', ['course_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'generation_runs', type_='foreignkey')
    op.drop_index(op.f('ix_generation_runs_course_id'), table_name='generation_runs')
    op.drop_column('generation_runs', 'course_id')
    # ### end Alembic commands ###
